### ISSUE TITLE
basemodel 中当含有NSArray的数据时，解析操作不彻底，导致最终的对象还是NSDictionary，从而导致crash

### ISSUE THREAD

**Issue by dayu1213** [OpenIMSDK/Open-IM-SDK-iOS#10]
![image](https://user-images.githubusercontent.com/16200552/147104582-18275e9c-4a44-4f66-a0a7-1f543478deb1.png)

**Comment by frcc00** [comment]
已提交1.0.20。我未创造条件测试，麻烦老哥跑一下，看是否解决。

**Comment by dayu1213** [comment]
测试了一下解决了，我只测了groupinfo
