### ISSUE TITLE
发送图片时出现账号被禁止错误

### ISSUE THREAD

**Issue by dayu1213** [OpenIMSDK/Open-IM-SDK-iOS#12]
图片，语音，视频，文件都出现，只有文字可以正常发送
log详情，
sendMessage errCode 301  errMsg Optional("PUT https://echat-1302656840.cos.ap-chengdu.myqcloud.com/1640502296212601000-8267293389953062911.heic: 451 UnavailableForLegalReasons(Message: Your account has been banned for the reason of violations, please delete the illegal objects., RequestId: NjFjODE0MThfOGNhNTU4NjRfYTlmZl8xNjZlMjA1, TraceId: OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTY4OGQ5OWY4YWFhNjAzOTkyNDJhZmQyOTk1YWVmOWFlMzYyNzU5YWE3ODgzZmM4N2I3Mzk0YjQxZGE0ODRkMWI=)")

**Comment by frcc00** [comment]
图片转成png（UIImagePNGRepresentation）

**Comment by dayu1213** [comment]
视频和语音呢？

**Comment by dayu1213** [comment]
代码没有改变，这个问题是突然出现的，可能和sdk更新有关

**Comment by frcc00** [comment]
cos好像出了点问题，稍等他们修复

**Comment by dayu1213** [comment]
ok，应该是，目前又可以了
