### ISSUE TITLE
发送消息的成功回调里获取历史消息,没有最新发送的消息

### ISSUE THREAD

**Issue by easydeleroy** [OpenIMSDK/Open-IM-SDK-iOS#20]
我写了重发消息的逻辑,先调用了删除本地的那条消息,然后创建一条新的消息,发送消息,在发送消息的成功回调里获取历史消息,没有这条新发的消息.
在发送消息中的成功回调里直接调用获取历史消息,也没有这条新消息
可能是消息还没加到本地数据库中,就成功回调了

**Comment by std-s** [comment]
> 我写了重发消息的逻辑,先调用了删除本地的那条消息,然后创建一条新的消息,发送消息,在发送消息的成功回调里获取历史消息,没有这条新发的消息. 在发送消息中的成功回调里直接调用获取历史消息,也没有这条新消息 可能是消息还没加到本地数据库中,就成功回调了

请更新sdk至2.0.6。
