### ISSUE TITLE
iOS12.1 pod导入SDK之后启动闪退，其他机型启动正常

### ISSUE THREAD

**Issue by appleLK** [OpenIMSDK/Open-IM-SDK-iOS#22]
![3801652946629_ pic](https://user-images.githubusercontent.com/18184062/169246885-e7d1ae27-d2b4-42f3-b79b-b371914f1106.jpg)

**Comment by std-s** [comment]
> ![3801652946629_ pic](https://user-images.githubusercontent.com/18184062/169246885-e7d1ae27-d2b4-42f3-b79b-b371914f1106.jpg)

可能和其它sdk产生的关联问题，请排查下。

**Comment by appleLK** [comment]
demo也是这样呢

**Comment by printlin** [comment]
Hello, I also found that the SDK does not support iOS 12 system, causing the app to crash every time it is opened. I noticed in the gomobile documentation that there is mention of the -iosversion option, which defaults to 13.0. After modifying it to 12.0 and recompiling, the app can run normally. Please note that this method is for reference only, and thorough testing is recommended. You can find information about gomobile at: https://pkg.go.dev/golang.org/x/mobile@v0.0.0-20240320162201-c76e57eead38/cmd/gomobile. You need to modify the compilation instructions for iOS in the openim-sdk-core/Makefile at line 221, adding -iosversion 12.0. After modification, it should look like this: GOARCH=arm64 gomobile bind -v -trimpath -iosversion 12.0 -ldflags "-s -w" -o build/OpenIMCore.xcframework -target=ios ./open_im_sdk/ ./open_im_sdk_callback/.
