### ISSUE TITLE
sdk 2.3.4.1报错 InsertMessage()@36: InsertMessage failed: sql: database is closed]，是什么错误？

### ISSUE THREAD

**Issue by jimckylin** [OpenIMSDK/Open-IM-SDK-iOS#24]
如题，是sdk本地报错还是服务端

**Comment by std-s** [comment]
sdk报的错误。 你看下OpenIMSDKCore是哪个版本 ？ 另外是如何复现的这个问题呢 ？

**Comment by jimckylin** [comment]
sdk 2.3.4.1的版本，进入login后退出调用logout方法，再进入login，发消息保错，在iphone8模拟器会必现，请问是sdk报错还是im服务器报的错呢？

**Comment by jimckylin** [comment]
OpenIMSDKCore (= 2.3.4)

**Comment by std-s** [comment]
@jimckylin  把控制台打印的日志，全拷贝出来。
