### ISSUE TITLE
从2.3.4.1 更新到2.3.4.3打包编译报错！

### ISSUE THREAD

**Issue by jimckylin** [OpenIMSDK/Open-IM-SDK-iOS#25]
从2.3.4.1 更新到2.3.4.3打包编译报错，模拟器编译运行没问题；再降回2.3.4.1，同样的问题，只能模拟器运行，打包编译报错，并且报了一推错误（xcode版本 13.4.1）：
Undefined symbols for architecture arm64:
  "_objc_msgSend$setObject:forKeyedSubscript:", referenced from:
      -[RefTracker assignRefnumAndIncRefcount:] in OpenIMCore(000009.o)
  "_objc_msgSend$intValue", referenced from:
      -[RefTracker assignRefnumAndIncRefcount:] in OpenIMCore(000009.o)
  "_objc_msgSend$objectForKeyedSubscript:", referenced from:
      -[RefTracker get:] in OpenIMCore(000009.o)
  "_objc_msgSend$cnt", referenced from:
      -[RefTracker dec:] in OpenIMCore(000009.o)
      -[RefTracker inc:] in OpenIMCore(000009.o)
      -[RefTracker assignRefnumAndIncRefcount:] in OpenIMCore(000009.o)
  "_objc_msgSend$getBytes:maxLength:usedLength:encoding:options:range:remainingRange:", referenced from:
      _go_seq_from_objc_string in OpenIMCore(000009.o)
  "_objc_msgSend$stringWithFormat:", referenced from:
      _go_seq_go_to_refnum in OpenIMCore(000009.o)
      _go_seq_from_objc_bytearray in OpenIMCore(000009.o)
      _go_seq_from_objc_string in OpenIMCore(000009.o)
      -[GoSeqRef init] in OpenIMCore(000009.o)
      -[RefTracker dec:] in OpenIMCore(000009.o)
      -[RefTracker inc:] in OpenIMCore(000009.o)
      -[RefTracker get:] in OpenIMCore(000009.o)

**Comment by std-s** [comment]
@jimckylin  pod cache clean OpenIMSDKCore --all ，把它的缓存全清了，再拉一下，看下情况。
