### ISSUE TITLE
OIMCallbacker+Closure 中丢失 onRecvNewMessage 赋值

### ISSUE THREAD

**Issue by sapherise** [OpenIMSDK/Open-IM-SDK-iOS#27]
> `- (void)setAdvancedMsgListenerWithOnRecvMessageRevoked:(OIMStringCallback)onRecvMessageRevoked
>                                   onRecvC2CReadReceipt:(OIMReceiptCallback)onRecvC2CReadReceipt
>                                 onRecvGroupReadReceipt:(OIMReceiptCallback)onRecvGroupReadReceipt
>                                       onRecvNewMessage:(OIMMessageInfoCallback)onRecvNewMessage {
>     self.onRecvMessageRevoked = onRecvMessageRevoked;
>     self.onRecvC2CReadReceipt = onRecvC2CReadReceipt;
>     self.onRecvGroupReadReceipt = onRecvGroupReadReceipt;
> }`

应添加

> `self.onRecvNewMessage = onRecvNewMessage;`

**Comment by std-s** [comment]
thx.
