### ISSUE TITLE
下载哪个分支的代码可以跑起来看功能效果

### ISSUE THREAD

**Issue by zp18862956943** [OpenIMSDK/Open-IM-SDK-iOS#3]
目前想下载个iOS的原生demo看看运行效果，了解大概有哪些功能，可是目前master分支下载的 跑起来报错，之前下载的EEChat 能跑起来，但是无法登录，求告知

**Comment by frcc00** [comment]
暂时没有原生demo，之前swift版的有功能缺失。我们尽快补上。

**Comment by frcc00** [comment]
demo：https://github.com/OpenIMSDK/Open-IM-iOS-Demo
