### ISSUE TITLE
🤖Failing-test: Open_im_sdkCreateTextMessage() return empty string.

### ISSUE THREAD

**Issue by boxiu** [OpenIMSDK/Open-IM-SDK-iOS#30]
### Which job are failing?

NSString *json = Open_im_sdkCreateTextMessage([OIMManager.manager operationId], text);

text is valid.

json is @""

### Which test are failing?

iOS APP
send text message ERROR

### Since when has it been failing?

send text message ERROR

**Comment by std-s** [comment]
@boxiu 
1. Confirm whether the login is successful;
2. Confirm whether the input parameters are correct;
3. If both of the above are correct, please post the log of the creation message here.

**Comment by std-s** [comment]
hi, It's been a long time since I saw your reply, so I'll close this question first.
