### ISSUE TITLE
Bug: <describe the error>

### ISSUE THREAD

**Issue by QiuYeHong90** [openimsdk/open-im-sdk-ios#31]
### What happened?

为什么应用在后台无法收到消息

### What did you expect to happen?

为什么应用在后台无法收到消息

### How can we reproduce it (as minimally and precisely as possible)?

为什么应用在后台无法收到消息

### Anything else we need to know?

为什么应用在后台无法收到消息

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

为什么应用在后台无法收到消息

### Cloud provider

<details>
</details>

为什么应用在后台无法收到消息

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

为什么应用在后台无法收到消息

### Install tools

<details>
</details>

为什么应用在后台无法收到消息

**Comment by std-s** [comment]
@QiuYeHong90 hi, Due to the iOS mechanism, you can find a way to keep the program from being suspended.

**Comment by std-s** [comment]
It hasn't responded for a long time, so I'll close it first.
