### ISSUE TITLE
Bug: iOS_OIMGroupListener_onGroupDismissed, no reply

### ISSUE THREAD

**Issue by LwqDeveloper** [openimsdk/open-im-sdk-ios#32]
### What happened?

i dismiss group from server, iOS didn't receive onGroupDismissed, Android has the same problem 

### What did you expect to happen?

dismiss group from server, receive listener from onGroupDismissed

### How can we reproduce it (as minimally and precisely as possible)?

easy to test it

### version

<details>
OpenIMSDK (~> 3.3.0)
</details>

### Cloud provider

<details>
none
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by std-s** [comment]
Okay, let's follow up.

**Comment by std-s** [comment]
```swift
/**
 *  Group has been disbanded.
 */
- (void)onGroupDismissed:(OIMGroupInfo *)changeInfo;
```
