### ISSUE TITLE
Bug: 卸载重装app登录后，onJoinedGroupAdded会被莫名奇妙回调很多次。

### ISSUE THREAD

**Issue by xq-120** [openimsdk/open-im-sdk-ios#33]
### What happened?

onJoinedGroupAdded method were called undesired when Uninstall and reinstall the app.

### What did you expect to happen?

not call

### How can we reproduce it (as minimally and precisely as possible)?

Uninstall and reinstall

### version

v3.3.0

### Cloud provider

<details>
</details>

### OS version

ios,16.5.1

### Install tools

<details>
</details>

**Comment by std-s** [comment]
Okay, let's follow up.

**Comment by std-s** [comment]
@xq-120  The current design is like this. Will it cause any problems?

**Comment by std-s** [comment]
There has been no response for a long time. Let me close this question first.
