### ISSUE TITLE
Bug: <describe the error>项目无法运行

### ISSUE THREAD

**Issue by laizhiVP** [openimsdk/open-im-sdk-ios#34]
### What happened?

下载的open-im-sdk-ios-master压缩包，OpenIMSDKiOS运行报错，
错误信息：Call to undeclared function 'Open_im_sdkGetUsersInfoWithCache'; ISO C99 and later do not support implicit function declarations

### What did you expect to happen?

无法运行

### How can we reproduce it (as minimally and precisely as possible)?

xcode15.0.1运行报错

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by std-s** [comment]
hi, use 'Open_im_sdkGetUsersInfoStranger' instead.

**Comment by laizhiVP** [comment]
你好，我使用Open_im_sdkGetUsersInfoStranger确实解决了之前的报错问题，但是依然报错，找不到Open_im_sdkCreateImageMessageByURL，并且是类似的问题，我看了一下，凡是在OpenIMCore这个库定义的，Open_im_sdk_callback.objc文件内的，我都找不到。我在网上查了一下也没找到一个合适的解决方法。

**Comment by std-s** [comment]
Hi, are you using version 3.3.0?
https://github.com/openimsdk/open-im-sdk-ios/releases/tag/3.3.0

**Comment by laizhiVP** [comment]
你好，我现在用你发的这个3.3.0，xcode15运行成功后什么都没有，xcode13运行后会有报错，功能无法正常使用
![xcode13](https://github.com/openimsdk/open-im-sdk-ios/assets/13550458/898cde51-e0e9-4cba-af17-1bfa06091837)

**Comment by std-s** [comment]
@laizhiVP  hi, you need to generate an account first.
It is recommended that you use the demo directly, it is easy to get started. 

https://github.com/openimsdk/open-im-ios-demo

**Comment by std-s** [comment]
There has been no response for a long time. Let me close this question first.
