### ISSUE TITLE
Bug: getUsersInfoWithCache No "ex" field returned

### ISSUE THREAD

**Issue by printlin** [openimsdk/open-im-sdk-ios#37]
### What happened?

The getUsersInfoWithCache function did not return the 'ex' field, although the documentation describes that it should return 'publicInfo.' Similarly, testing with the Android SDK confirmed that the 'ex' field is returned.

### What did you expect to happen?

return the 'ex' field

### How can we reproduce it (as minimally and precisely as possible)?

use getUsersInfoWithCache 100% reproduce it

### version

OpenIMSDK  3.5.1-alpha.2
or
OpenIMSDK 3.4.0

### Cloud provider

local

**Comment by printlin** [comment]
I found the reason. The 'EX' field is not defined in OIMPublicUserInfo in `OpenIMSDK/Model/OIMFullUserInfo.h`. Once I defined it, I was able to successfully retrieve it.

**Comment by std-s** [comment]
> I found the reason. The 'EX' field is not defined in OIMPublicUserInfo in `OpenIMSDK/Model/OIMFullUserInfo.h`. Once I defined it, I was able to successfully retrieve it.

Thanks for finding it, will update later.
