### ISSUE TITLE
[API design]: Why not return conversation synchronously?

### ISSUE THREAD

**Issue by AnnaSearl** [openimsdk/open-im-sdk-ios#39]
### What would you like to share?

I found that the API related to get conversation in the document are all asynchronous. Why don't they return synchronously? This will be more convenient and easier to use.
![image](https://github.com/openimsdk/open-im-sdk-ios/assets/26404546/f4b0396f-8f25-419a-89c0-0efd4f38c377)
![image](https://github.com/openimsdk/open-im-sdk-ios/assets/26404546/c63ec329-001f-40f1-957e-d4961ad3c63a)
![image](https://github.com/openimsdk/open-im-sdk-ios/assets/26404546/3011265a-9d5a-496a-b797-c224f7bebf09)

**Comment by AnnaSearl** [comment]
Just like this 
`- (OIMConversationInfo *)getConversation:(NSString *)conversationId`

**Comment by std-s** [comment]
Hi, for UI smoothness.
