### ISSUE TITLE
getTotalUnreadMsgCount崩溃

### ISSUE THREAD

**Issue by zungjam** [OpenIMSDK/Open-IM-SDK-iOS#4]
getAllConversationList一样也崩溃
机型：iPhone 12 Pro Max
系统：iOS 15.1

SDK已初始化并登录成功

<img width="1374" alt="WX20211123-234420@2x" src="https://user-images.githubusercontent.com/16434431/143057903-be8b4c8f-b304-4e30-ac54-66514026e0bd.png">

**Comment by frcc00** [comment]
onSuccess和onError是否设置为了nil?

**Comment by frcc00** [comment]
我优化下类似的调用

**Comment by zungjam** [comment]
> onSuccess和onError是否设置为了nil?

暂时都只是print

**Comment by frcc00** [comment]
> 

好

**Comment by frcc00** [comment]
> > onSuccess和onError是否设置为了nil?
> 
> 暂时都只是print

需要在login的onSuccess回调成功后，才能调用其他方法。

**Comment by zungjam** [comment]
> > > onSuccess和onError是否设置为了nil?
> > 
> > 
> > 暂时都只是print
> 
> 需要在login的onSuccess回调成功后，才能调用其他方法。

是的，这点注意到了，确保了login成功的，日志里打印了用户信息，但还是崩溃

**Comment by frcc00** [comment]
麻烦提供下出错截图

**Comment by zungjam** [comment]
> 麻烦提供下出错截图。我这边没重现。

<img width="816" alt="image" src="https://user-images.githubusercontent.com/16434431/143202519-8ee59c86-9677-46a7-9261-1fe7d5ffe84a.png">
iOS这边晚上提供截图，刚才安卓表示也遇到了同样的错误

**Comment by zungjam** [comment]
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/16434431/143240130-f300d1dc-b099-4d0c-a1f7-a506a2d79a2d.png">
iOS也是在这里崩溃

**Comment by zungjam** [comment]
找到原因了，每次打开App都必须调用一次login才能调用其他方法，建议修改成SDK内部保存登录状态或者提供文档注明每次App Launch都必须login。

**Comment by frcc00** [comment]
h好的
