### ISSUE TITLE
I want to support iOS 12, which version of SDK should I choose?

### ISSUE THREAD

**Issue by AnnaSearl** [openimsdk/open-im-sdk-ios#40]
### What would you like to share?

I want to support iOS 12, but the latest version only supports iOS 13. Which version of SDK should I choose?

**Comment by std-s** [comment]
Hi, Can support iOS11.

**Comment by AnnaSearl** [comment]
> Hi, Can support iOS11.

But during the build process I found this warning:
![image](https://github.com/openimsdk/open-im-sdk-ios/assets/26404546/7e5106bd-e7a3-4f9b-9607-5b980ceee4f0)

**Comment by std-s** [comment]
Does not affect the compiler.
