### ISSUE TITLE
Bug: Don't get OIMMessageContentTypeTyping news

### ISSUE THREAD

**Issue by tianyu9090** [openimsdk/open-im-sdk-ios#42]
### What happened?

- (void)onRecvNewMessage:(OIMMessageInfo *)msg{

}

Don't get OIMMessageContentTypeTyping news

### What did you expect to happen?

Another user is typing

### How can we reproduce it (as minimally and precisely as possible)?

Another user is typing

### Anything else we need to know?

It can be received using v3.5.0-rc1。

### version

iOS V3.5.1 add Vv3.5.1-alpha.8 

### Cloud provider

pod 'OpenIMSDK', '~> 3.5.1-alpha.8'  
Or
pod 'OpenIMSDK', '~> 3.5.1'

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by tianyu9090** [comment]
I read the latest version, and there's a method
- (void)onConversationUserInputStatusChanged:(NSString *)change {

}
It is possible to get the user's input status, but this feature is not fully developed

**Comment by std-s** [comment]
hi, Use them together.
```swift
/**
 * Typing status for one-on-one chat
 *
 * @param conversationID    Receiver's ID
 * @param focus    Customized tip message
 */
- (void)changeInputStates:(NSString *)conversationID
                    focus:(BOOL)focus
                 onSuccess:(nullable OIMSuccessCallback)onSuccess
                 onFailure:(nullable OIMFailureCallback)onFailure;

/**
 * Typing status for one-on-one chat
 *
 * @param conversationID    Conversation's ID
 * @param userID    User's ID
 */
- (void)getInputstates:(NSString *)conversationID
                userID:(NSString *)userID
             onSuccess:(nullable OIMInputStatusChangedCallback)onSuccess
             onFailure:(nullable OIMFailureCallback)onFailure;
@end
```

**Comment by tianyu9090** [comment]
I'm using pod 'OpenIMSDK', '~> 3.5.1'.
I didn’t see the method api you posted.
/**
 * Typing status for one-on-one chat
 *
 * @param conversationID    Receiver's ID
 * @param focus    Customized tip message
 */
- (void)changeInputStates:(NSString *)conversationID
                    focus:(BOOL)focus
                 onSuccess:(nullable OIMSuccessCallback)onSuccess
                 onFailure:(nullable OIMFailureCallback)onFailure;

/**
 * Typing status for one-on-one chat
 *
 * @param conversationID    Conversation's ID
 * @param userID    User's ID
 */
- (void)getInputstates:(NSString *)conversationID
                userID:(NSString *)userID
             onSuccess:(nullable OIMInputStatusChangedCallback)onSuccess
             onFailure:(nullable OIMFailureCallback)onFailure;

**Comment by std-s** [comment]
@tianyu9090 Will be added soon.
