### ISSUE TITLE
The iOS platform cannot receive data in the description field of OIMCustomElem sent by other platforms [BUG]

### ISSUE THREAD

**Issue by JulianSong** [openimsdk/open-im-sdk-ios#44]
### OpenIM Server Version

3.7.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

iOS平台无法接收其他平台发送的 OIMCustomElem 的description字段的数据

### Screenshots Link

<img width="935" alt="Snipaste_2024-06-06_15-54-15" src="https://github.com/openimsdk/open-im-sdk-ios/assets/2277048/800e36cd-038b-4c81-aae1-a74eebef674d">

**Comment by std-s** [comment]
Hi, use the latest sdk.

**Comment by liu-xs** [comment]
请问解决这个问题的pr 可以说一下是哪个吗

> Hi, use the latest sdk.

**Comment by youngbody** [comment]
server use 3.5.1， sdk use 3.8，is that work？
