### ISSUE TITLE
[BUG]  群聊发送图片、语音、视频失败，单聊能发送成功，sdk2.2的demo也是一样的

### ISSUE THREAD

**Issue by CoderMC** [openimsdk/open-im-sdk-ios#45]
### OpenIM Server Version

2.2

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

群聊发送图片、语音、视频失败，单聊能发送成功，sdk2.2的demo也是一样的

**Comment by CoderMC** [comment]
返回的错误码 301，哪里可以查看对应的错误信息啊。send message error: Optional("operationID[1719629170547], info[==> open_im_sdk/internal/obj_storage.(*COS).uploadObj()@98: : ==> open_im_sdk/internal/obj_storage.(*COS).tencentCOSCredentials()@52: : ==> open_im_sdk/pkg/common.CheckErrAndResp()@154: : unexpected end of JSON input]8f0fb9d9e746c646e576f4caa08fb411 ")  这个代表什么意思

**Comment by std-s** [comment]
Hi, it is recommended to upgrade to v3.
