### ISSUE TITLE
[BUG] The nickname avatar in stranger chat, conversation list and history messages is not the latest

### ISSUE THREAD

**Issue by wozaihu** [openimsdk/open-im-sdk-ios#49]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

举例：A和B有会话记录，当B通过setSelfInfo修改了自己的昵称和头像，A通过getAllConversationList中的ConversationInfo 和getAdvancedHistoryMessageList 中的Message 获取不到B最新的昵称和头像，导致A显示的总是B旧的昵称和头像，A收到B的新消息时Message中是B新头像和昵称，但退出会话页面重新打开会调用getAdvancedHistoryMessageList，这又只能显示旧的昵称和头像了，这是bug吗，要怎么处理。

备注：
没有在服务端维护好友关系，所以所有人都是陌生人聊天。

**Comment by std-s** [comment]
It will be updated after calling getUserInfo.

**Comment by wozaihu** [comment]
> It will be updated after calling getUserInfo.

thanks you
