### ISSUE TITLE
ios demo message发送没有回调相应

### ISSUE THREAD

**Issue by dayu1213** [OpenIMSDK/Open-IM-SDK-iOS#5]
发送text message 和image message 没有成功或者失败的回调相应。在发送image message时只收到 progress的回调。

**Comment by frcc00** [comment]
方便发个截图吗？我没重现。

**Comment by dayu1213** [comment]
![image](https://user-images.githubusercontent.com/16200552/143800495-2dff0aba-573b-40bd-9c45-998143bfc827.png)

**Comment by dayu1213** [comment]
会不会使我们搭建的服务器问题，因为这个调用很简单，就一行代码调用。我把token和我们服务器地址发你你能给我确认一下吗？

**Comment by dayu1213** [comment]
http://8.142.13.232:10000
ws://8.142.13.232:30000
sendID=1442969940624670720&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVSUQiOiIxNDQyOTY5OTQwNjI0NjcwNzIwIiwiUGxhdGZvcm0iOiJJT1MiLCJleHAiOjE2Mzg0NDY4NDMsIm5iZiI6MTYzNzg0MjA0MywiaWF0IjoxNjM3ODQyMDQzfQ.4ADjQ-DJ0ZAdXR2q1hpAmECQGvWGQmHFuEadpS4CwOo

**Comment by frcc00** [comment]
使用你给的服务器确实没有回调

**Comment by frcc00** [comment]
可以更新一下试试

**Comment by dayu1213** [comment]
更新什么？如何操作呢？

**Comment by dayu1213** [comment]
能确认是我们这面搭建的服务器问题吗？

**Comment by frcc00** [comment]
> 更新什么？如何操作呢？

确认下docker的版本，看有没有更新

**Comment by frcc00** [comment]
> 能确认是我们这面搭建的服务器问题吗？

这个不好说，服务器用的特殊分支的docker？

**Comment by dayu1213** [comment]
我先找后台同事看一下。

**Comment by dayu1213** [comment]
问题定位在服务器版本不是最新的，将服务器更新至最新即可
