### ISSUE TITLE
[BUG] Upload img or voice report error msg:unexpected end of JSON input, code:10002

### ISSUE THREAD

**Issue by pengxu1013** [openimsdk/open-im-sdk-ios#51]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

macOS (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

Error 10002 was reported when the network image and voice were uploaded. The error message was unexpected end of JSON input。The demo will report the same error,Uploaded using the "sendMessageNotOss" method
![2](https://github.com/user-attachments/assets/c9455173-c246-4289-aaac-c3c544eeaed6)
![3](https://github.com/user-attachments/assets/9392085d-ee14-443a-b52c-a26c644d94c3)

**Comment by ptisnoob** [comment]
same issues

**Comment by std-s** [comment]
@pengxu1013 , @ptisnoob  offlinePushInfo cannot be nil. The parameter restrictions will be adjusted in the next version.

**Comment by ptisnoob** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
