### ISSUE TITLE
[BUG] The background crashes when entering the foreground, the chat link is slow, and the message sending and receiving are slow

### ISSUE THREAD

**Issue by awindyseason** [openimsdk/open-im-sdk-ios#53]
### OpenIM Server Version

3.5.1/ 3.8.1

### Operating System and CPU Architecture

iPhone

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

接入3.5.1sdk能进行正常的收发消息，但是放置在后台一段时间大概10分钟后再重新进入app会闪退。当我不使用sdk后，就正常了。
更新到3.8.1后闪退好像没发生了。但是在收发消息变得很慢，特别是第一次进入聊天会话，发送消息，会等待好几秒。

**Comment by std-s** [comment]
After upgrading to 3.8, post the log of this situation.

**Comment by awindyseason** [comment]
> After upgrading to 3.8, post the log of this situation.

已经升级了最新的3.8 ，使用sdk调用了 uploadLogsWithProgress 。 
在第一次打开app时 发送消息要等几秒。另一台手机收到红点会有延迟，并且另一台手机打开进入聊天历史信息出现了丢失获取不到的情况。

**Comment by awindyseason** [comment]
在3.5.1上，无论怎么退出重进app，收发消息都是正常的，，也不会出现明显的延迟和历史消息加载不出的情况,在3.8上则聊天会经常出现问题。

**Comment by awindyseason** [comment]
3.8进入聊天会话会一直触发initSDKWithConfig的onConnecting 跟onConnectSuccess的回调方法

**Comment by std-s** [comment]
> 3.8进入聊天会话会一直触发initSDKWithConfig的onConnecting 跟onConnectSuccess的回调方法

Maybe it's not connecting to the server?
