### ISSUE TITLE
[BUG] insertSingleMessageToLocalStorage reports error 10005, for example, InsertMessage failed: no such table: chat_logs_si_1794197_1801541

### ISSUE THREAD

**Issue by ChingFai51866** [openimsdk/open-im-sdk-ios#57]
### OpenIM Server Version

3.5.1

### Operating System and CPU Architecture

macOS (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

退出登陆，登陆其他账号之后，此API会出现报错，code码10005，error *errors.withStack not implement CodeError: ==> github.com/openimsdk/openim-sdk-core/v3/pkg/db.(*DataBase).InsertMessage()@73: InsertMessage failed: no such table: chat_logs_si_1794197_1801541

**Comment by std-s** [comment]
@ChingFai51866 Hi, what is the scenario? Non-friends have never chatted to call this function?

**Comment by std-s** [comment]
There has been no news for a long time, so I will close this issue first.
