### ISSUE TITLE
[BUG] pinConversation doesn't work on C2C conversation on iOS SDK v3.8.1+1

### ISSUE THREAD

**Issue by YanjieZhao** [openimsdk/open-im-sdk-ios#60]
### OpenIM Server Version

3.8.1+1

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

When I invoke pinConversation for a C2C conversation, it doesn't work.
I use swift and xcode 16.
I have updated sdk to version 3.8.1+1, the issue persists.

**Comment by std-s** [comment]
@YanjieZhao  Hi, using 3.8.1+2.

**Comment by YanjieZhao** [comment]
> @YanjieZhao Hi, using 3.8.1+2.

It works, thanks.
