### ISSUE TITLE
[BUG] notificationElem.opUser.nickname the value sometimes is imAdmin not real user name

### ISSUE THREAD

**Issue by winterrain5** [openimsdk/open-im-sdk-ios#63]
### OpenIM Server Version

3.5.1

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

1、create a group 
2、sdk return a message,the contentType is createGroup
3、get opUser.name,but the name is imAdmin

### Screenshots Link

![IMG_0756](https://github.com/user-attachments/assets/6f35c95b-afd0-4dd0-9859-b5d48c18c06f)

**Comment by std-s** [comment]
Hi, updated to 3.8.

**Comment by winterrain5** [comment]
version was updated to 3.8 but problem is exist,and bring a new problem,getGroupMemberList is return error.

**Comment by std-s** [comment]
Hi, you can try the [Demo](https://github.com/openimsdk/open-im-ios-demo)

**Comment by std-s** [comment]
It has not responded for a long time. Close it first and reopen it when there is a problem.
