### ISSUE TITLE
[BUG] change group introduction,but the message return is group name changed

### ISSUE THREAD

**Issue by winterrain5** [openimsdk/open-im-sdk-ios#64]
### OpenIM Server Version

3.5.1

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

1、use api setGroupInfo,set introduction property
2、return a message，but the message contentType is groupSetName

**Comment by std-s** [comment]
Hi, updated to 3.8.

**Comment by std-s** [comment]
It has not responded for a long time. Close it first and reopen it when there is a problem.
