### ISSUE TITLE
iOS 收发消息不成功

### ISSUE THREAD

**Issue by Yan-jinwei** [OpenIMSDK/Open-IM-SDK-iOS#7]
在运行iOS端Example示例的时候，初始化和登录是成功的，但是发送和接收消息，控制台均会报错（截图已通过附件上传），消息列表的监听都没有收到回调，请问这应该如何处理呢？

<img width="1137" alt="WX20211211-181657@2x" src="https://user-images.githubusercontent.com/67769694/145673039-d2d159af-4b70-4b63-87b2-abea707251e9.png">

<img width="1126" alt="WX20211211-181858@2x" src="https://user-images.githubusercontent.com/67769694/145673049-18b634f2-fa66-44f5-a17c-e78f57053467.png">

<img width="1125" alt="WechatIMG2264" src="https://user-images.githubusercontent.com/67769694/145673057-91c4b179-421b-4cf3-960a-a78e746f35f6.png">

![WechatIMG2283](https://user-images.githubusercontent.com/67769694/145673060-186dc7b2-09f9-4669-ab70-1c2e2e8ed474.jpeg)

**Comment by frcc00** [comment]
看下server的docker版本，升级一下

**Comment by Yan-jinwei** [comment]
server同步版本后已解决，谢谢
