### ISSUE TITLE
markC2CMessage 标记已读无效

### ISSUE THREAD

**Issue by dayu1213** [OpenIMSDK/Open-IM-SDK-iOS#8]
ios调用此API标记消息已读无效，还是显示未读，而且未读消息数目也不会变化

**Comment by dayu1213** [comment]
![image](https://user-images.githubusercontent.com/16200552/147014705-3ecae9fc-1428-4245-86e2-90e6bc37f9d1.png)

**Comment by dayu1213** [comment]
这个什么时候能解决啊

**Comment by frcc00** [comment]
> 这个什么时候能解决啊

我更新下core看看

**Comment by frcc00** [comment]
1.0.22已提交，麻烦测试下

**Comment by dayu1213** [comment]
可以标记为已读，但是未读消息数量不会变化

**Comment by dayu1213** [comment]
好像并没有作用，还是不能标记为已读，未读数量也不会变化

**Comment by frcc00** [comment]
其他的标记已读方法，有没有用？

**Comment by dayu1213** [comment]
其他的可以用，标记对话为已读的就可以，标记组消息已读的也可以，

**Comment by frcc00** [comment]
那等服务端修复吧

**Comment by dayu1213** [comment]
有进展吗？

**Comment by dayu1213** [comment]
这个问题有更新吗？

**Comment by frcc00** [comment]
c2c是用于消息已读状态的置位
c2c是接收消息的人调用
未读消息数通过另外一个API改变
markSingleMessageHasRead\markGroupMessageHasRead
调用过后发消息的人会收到另一个回调
OnRecvC2CReadReceipt
通过收到的消息id对当前界面上的消息进行置位

**Comment by frcc00** [comment]
你看看有没有帮助

**Comment by dayu1213** [comment]
markSingleMessageHasRead这个是标记单个聊天所有消息已读状态的 ，有标记单条消息已读状态的吗？另外c2c是用于消息已读状态的置位是什么意思，这个不是消息接收人标记自己是否已读这条消息吗？如果接受者调用markSingleMessageHasRead，那么c2c还有什么用呢，因为整个聊天的消息状态都被标记为已读了

**Comment by dayu1213** [comment]
message的isRead属性，是用来标记接受还是发送方的，那些api会对此属性改变呢/?

**Comment by frcc00** [comment]
比如你给我发了消息，我进入了聊天界面就程序就可以认为我读了，调用markSingleMessageHasRead\markGroupMessageHasRead，你那么会有执行OnRecvC2CReadReceipt，然后在你界面上展示我已经读了消息

**Comment by frcc00** [comment]
isRead简单理解就是别人读没读。OnRecvC2CReadReceipt的方法里执行markC2CMessage就完了，界面根据isRead做展示。

**Comment by frcc00** [comment]
> markSingleMessageHasRead这个是标记单个聊天所有消息已读状态的 ，有标记单条消息已读状态的吗？另外c2c是用于消息已读状态的置位是什么意思，这个不是消息接收人标记自己是否已读这条消息吗？如果接受者调用markSingleMessageHasRead，那么c2c还有什么用呢，因为整个聊天的消息状态都被标记为已读了

好像并没有需要标记单条的场景，只要用户进入聊天界面，就应该认为已读了所有消息。

**Comment by frcc00** [comment]
> markSingleMessageHasRead这个是标记单个聊天所有消息已读状态的 ，有标记单条消息已读状态的吗？另外c2c是用于消息已读状态的置位是什么意思，这个不是消息接收人标记自己是否已读这条消息吗？如果接受者调用markSingleMessageHasRead，那么c2c还有什么用呢，因为整个聊天的消息状态都被标记为已读了

目前没有标记单条消息的接口

**Comment by dayu1213** [comment]
我自己可以更新message的isread属性对吗？

**Comment by frcc00** [comment]
> 我自己可以更新message的isread属性对吗？

对
